import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#f9f9f9",
        surface: "#f9f9f9",
        "on-surface-variant": "#4d4635",
        "tertiary-container": "#97b0ff",
        secondary: "#5e604d",
        "surface-variant": "#e2e2e2",
        "inverse-surface": "#2f3131",
        "surface-bright": "#f9f9f9",
        "on-background": "#1a1c1c",
        "inverse-primary": "#e9c349",
        primary: "#735c00",
        "secondary-fixed-dim": "#c8c8b0",
        "on-secondary": "#ffffff",
        "outline-variant": "#d0c5af",
        "on-primary-fixed": "#241a00",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#27438a",
        "tertiary-fixed": "#dbe1ff",
        "on-tertiary-container": "#254188",
        outline: "#7f7663",
        "on-secondary-fixed-variant": "#474836",
        error: "#ba1a1a",
        "on-secondary-container": "#636451",
        "on-primary-container": "#554300",
        "secondary-container": "#e1e1c9",
        "on-surface": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed-dim": "#e9c349",
        tertiary: "#415ba4",
        "tertiary-fixed-dim": "#b4c5ff",
        "surface-container": "#eeeeee",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#e4e4cc",
        "on-secondary-fixed": "#1b1d0e",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dadada",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffe088",
        "on-tertiary-fixed": "#00174b",
        "primary-container": "#d4af37",
        "inverse-on-surface": "#f0f1f1",
        "surface-container-high": "#e8e8e8",
        "surface-tint": "#735c00",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#574500",
        "surface-container-low": "#f3f3f4",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1200px",
        gutter: "24px",
        unit: "8px",
        "margin-desktop": "48px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
